### ISSUE TITLE
Privileged Intent usage

### ISSUE THREAD

**Issue by YorkAARGH** [Thatcooldevguy/BetterDiscordUtils#1]
If you're going to offer up a utility function that deals with serving up user presence data, inform the bot developer that enabling the intent will be required, and will increase their memory consumption every time that utility is used.

**Comment by Thatcooldevguy** [comment]
Thanks for your feedback, York! 

We'll be sure to add the warning.

**Comment by Thatcooldevguy** [comment]
Hey @YorkAARGH, We've added your idea to main. Feel free to take alook at the new code.
